# Generated by Django 3.2.3 on 2021-05-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotto',
            fields=[
                ('cnt', models.IntegerField(primary_key=True, serialize=False)),
                ('lottono', models.CharField(db_column='lottoNo', max_length=80)),
                ('bnusno', models.IntegerField(db_column='bnusNo')),
                ('firstwinamnt', models.BigIntegerField(blank=True, db_column='firstWinamnt', null=True)),
                ('secondwinamnt', models.BigIntegerField(blank=True, db_column='secondWinamnt', null=True)),
                ('thirdwinamnt', models.IntegerField(blank=True, db_column='thirdWinamnt', null=True)),
                ('fourthwinamnt', models.IntegerField(blank=True, db_column='fourthWinamnt', null=True)),
                ('fifthwinamnt', models.IntegerField(blank=True, db_column='fifthWinamnt', null=True)),
            ],
            options={
                'db_table': 'lotto',
                'managed': False,
            },
        ),
    ]
