# Generated by Django 3.2.3 on 2021-05-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
