# Generated by Django 3.2.3 on 2021-06-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0002_usernum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, db_column='nickname', max_length=100, null=True)),
                ('num', models.CharField(blank=True, db_column='num', max_length=80, null=True)),
                ('price', models.BigIntegerField(blank=True, db_column='price', null=True)),
            ],
            options={
                'db_table': 'ranking',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserNum',
        ),
    ]
